version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: nagging-postgres-container
    ports:
      - "5433:5432" # 포트도 확실하게 5433으로 고정!
    environment:
      POSTGRES_DB: momsnagging
      POSTGRES_USER: postgres # 주의: application.yml에 적힌 username과 같아야 함!
      POSTGRES_PASSWORD: password # 주의: application.yml에 적힌 password와 같아야 함!
      TZ: Asia/Seoul
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: nagging-redis-container
    ports:
      - "${REDIS_PORT}:6379"
    restart: always